connector:
  jdbc:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moodle?zeroDateTimeBehavior=convertToNull
    username: arsnova
    password: arsnova

  # Select the data access object implementation your target platform
  # Uncomment the following line to access Moodle
  dao:
    implementation: MoodleConnectorDaoImpl
    # Uncomment the following line to access Stud.IP
    #implementation: StudipConnectorDaoImpl
    # Uncomment the following line to get a dummy implementation
    #implementation: DummyConnectorDaoImpl

  admin:
    username: arsnova
    password: arsnova

  ldap:
    serverUrl:
    userSearchBase:
    userSearchFilter:
