variables:
  OUTPUT_DIR: "*/build"
  GRADLE_USER_HOME: .gradle-user-home

.gradle:
  image: gradle:6.2-jdk8
  cache:
    key: gradle-global-cache
    paths:
      - $GRADLE_USER_HOME/caches

compile:
  extends: .gradle
  stage: build
  artifacts:
    paths:
      - $OUTPUT_DIR
  script:
    - gradle xjc assemble

unit_test:
  extends: .gradle
  stage: test
  dependencies:
    - compile
  artifacts:
    paths:
      - $OUTPUT_DIR
  script:
    - gradle test
